[package]
name = "ruscon"
version = "0.1.0"
authors = ["taito"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix="0.20.0"
anyhow = "1.0"
clap = "2.33.3"